version: '2'
services:
    reportgateway-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/reportgateway/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=reportgateway
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
